### ISSUE TITLE
Сделать фильтр событий в рамках одного отслеживания

### ISSUE THREAD

**Issue by Romarub** [AtrisFlax/ItHappened#13]
События фильтруются в рамках отслеживания. Не нужно фильтровать по всем событиям пользователя

**Comment by AtrisFlax** [comment]
В классе EventTrackerService сделать фильтрацию по времени

**Comment by Romarub** [comment]
"В классе EventTrackerService сделать фильтрацию по времени" - это нужно обсудить. Я что-то не понимаю. Это вроде должен движок статистики делать

**Comment by Romarub** [comment]
> В классе EventTrackerService сделать фильтрацию по времени

это нужно обсудить. Я что-то не понимаю. Это вроде должен движок статистики делать
