### ISSUE TITLE
Имена Трекеров для одного Пользвователя должны быть уникальными 

### ISSUE THREAD

**Issue by Romarub** [AtrisFlax/ItHappened#227]
добавить проверку в сервисе трекеров. 
При создании и редактировании трекеров выгружаем все трекеры пользователя и проверяем на совпадение имен.

**Comment by AtrisFlax** [comment]
Пытался решить проблему средствами БД. В таблице Trackers ограничил столбец Name с помощью Unique, но в таком случае разные пользователи не могли иметь совпадающие имена трекеров.

Пришел к решению описанному в pr request [1]

[1] https://github.com/MindboxDevSchool/ItHappened/pull/228
