### ISSUE TITLE
Статистика. Зафиксировано уже N событий

### ISSUE THREAD

**Issue by AtrisFlax** [AtrisFlax/ItHappened#30]
Атрибуты: EventsCount

Текстовое описание: "У вас произошло уже {EventsCount} событий!"

Приоритет: log(EventsCount)

Иллюстрация: нет

Функция применимости: применимо, если количество отслеживаний больше 0, суммарное количество событий больше 5. EventsCount - количество событий во всех отслеживаниях.

**Comment by SteppaM** [comment]
Реализация есть, нужны тесты.
