### ISSUE TITLE
Статистика. Отслеживания. Количество событий

### ISSUE THREAD

**Issue by AtrisFlax** [AtrisFlax/ItHappened#33]
Атрибуты: EventsCount

Текстовое описание: "Событие "{TrackingName}" произошло {EventsCount} раз"

Приоритет: log(EventsCount)

Иллюстрация: отсутствует

Функция применимости: применимо, если количество событий в целевом отслеживании больше 0

**Comment by SteppaM** [comment]
Реализация есть, нужны тесты
