### ISSUE TITLE
Статистика. Отслеживания. Самый долгий перерыв

### ISSUE THREAD

**Issue by AtrisFlax** [AtrisFlax/ItHappened#42]
Атрибуты: DurationInDays, LastEventBeforeBreakDate, FirstEventAfterBreakDate

Текстовое описание: "Самый большой перерыв в {TrackingName} произошёл с {LastEventBeforeBreakDate} до {FirstEventAfterBreakDate}, он занял {DurationInDays} дней"

Приоритет: sqrt(DurationInDays)

Иллюстрация: нет

Функция применимости: применимо, только если количество событий в отслеживании больше 10, FirstEventAfterBreakDate был более, чем неделю назад и DurationInDays в 3 или более раз больше, чем среднее время между событиями. DurationInDays - продолжительность самого длинного перерыва в днях, LastEventBeforeBreakDate - дата, когда произошло последнее перед этим перерывом событие, FirstEventAfterBreakDate - дата, когда произошло первое событие после перерыва.

**Comment by SteppaM** [comment]
Реализация есть, нужны тесты
